# Generated by Django 2.0.4 on 2018-04-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
                ('dataPub', models.DateTimeField(auto_now_add=True, verbose_name='Data odczytu')),
            ],
        ),
    ]
